//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.FFJudoServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ffjda_critt.org/", ConfigurationName="FFJudoServices.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément listeInscriptionsCRITTResult de l'espace de noms http://ffjda_critt.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ffjda_critt.org/listeInscriptionsCRITT", ReplyAction="*")]
        Tools.FFJudoServices.listeInscriptionsCRITTResponse listeInscriptionsCRITT(Tools.FFJudoServices.listeInscriptionsCRITTRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément listeClubsEventCRITTResult de l'espace de noms http://ffjda_critt.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ffjda_critt.org/listeClubsEventCRITT", ReplyAction="*")]
        Tools.FFJudoServices.listeClubsEventCRITTResponse listeClubsEventCRITT(Tools.FFJudoServices.listeClubsEventCRITTRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément listeClubsCRITTResult de l'espace de noms http://ffjda_critt.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ffjda_critt.org/listeClubsCRITT", ReplyAction="*")]
        Tools.FFJudoServices.listeClubsCRITTResponse listeClubsCRITT(Tools.FFJudoServices.listeClubsCRITTRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément Sexe de l'espace de noms http://ffjda_critt.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ffjda_critt.org/listeCategoriesPoidsCRITT", ReplyAction="*")]
        Tools.FFJudoServices.listeCategoriesPoidsCRITTResponse listeCategoriesPoidsCRITT(Tools.FFJudoServices.listeCategoriesPoidsCRITTRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément login de l'espace de noms http://ffjda_critt.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ffjda_critt.org/listeEventsCRITT", ReplyAction="*")]
        Tools.FFJudoServices.listeEventsCRITTResponse listeEventsCRITT(Tools.FFJudoServices.listeEventsCRITTRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément login de l'espace de noms http://ffjda_critt.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ffjda_critt.org/listePopulationCRITT", ReplyAction="*")]
        Tools.FFJudoServices.listePopulationCRITTResponse listePopulationCRITT(Tools.FFJudoServices.listePopulationCRITTRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément login de l'espace de noms http://ffjda_critt.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ffjda_critt.org/majResultatCRITT", ReplyAction="*")]
        Tools.FFJudoServices.majResultatCRITTResponse majResultatCRITT(Tools.FFJudoServices.majResultatCRITTRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément login de l'espace de noms http://ffjda_critt.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ffjda_critt.org/majResultatFFJDA", ReplyAction="*")]
        Tools.FFJudoServices.majResultatFFJDAResponse majResultatFFJDA(Tools.FFJudoServices.majResultatFFJDARequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément xml de l'espace de noms http://ffjda_critt.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ffjda_critt.org/test", ReplyAction="*")]
        Tools.FFJudoServices.testResponse test(Tools.FFJudoServices.testRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listeInscriptionsCRITTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listeInscriptionsCRITT", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.listeInscriptionsCRITTRequestBody Body;
        
        public listeInscriptionsCRITTRequest() {
        }
        
        public listeInscriptionsCRITTRequest(Tools.FFJudoServices.listeInscriptionsCRITTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class listeInscriptionsCRITTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEvent;
        
        public listeInscriptionsCRITTRequestBody() {
        }
        
        public listeInscriptionsCRITTRequestBody(int idEvent) {
            this.idEvent = idEvent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listeInscriptionsCRITTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listeInscriptionsCRITTResponse", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.listeInscriptionsCRITTResponseBody Body;
        
        public listeInscriptionsCRITTResponse() {
        }
        
        public listeInscriptionsCRITTResponse(Tools.FFJudoServices.listeInscriptionsCRITTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class listeInscriptionsCRITTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listeInscriptionsCRITTResult;
        
        public listeInscriptionsCRITTResponseBody() {
        }
        
        public listeInscriptionsCRITTResponseBody(string listeInscriptionsCRITTResult) {
            this.listeInscriptionsCRITTResult = listeInscriptionsCRITTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listeClubsEventCRITTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listeClubsEventCRITT", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.listeClubsEventCRITTRequestBody Body;
        
        public listeClubsEventCRITTRequest() {
        }
        
        public listeClubsEventCRITTRequest(Tools.FFJudoServices.listeClubsEventCRITTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class listeClubsEventCRITTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEvent;
        
        public listeClubsEventCRITTRequestBody() {
        }
        
        public listeClubsEventCRITTRequestBody(int idEvent) {
            this.idEvent = idEvent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listeClubsEventCRITTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listeClubsEventCRITTResponse", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.listeClubsEventCRITTResponseBody Body;
        
        public listeClubsEventCRITTResponse() {
        }
        
        public listeClubsEventCRITTResponse(Tools.FFJudoServices.listeClubsEventCRITTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class listeClubsEventCRITTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listeClubsEventCRITTResult;
        
        public listeClubsEventCRITTResponseBody() {
        }
        
        public listeClubsEventCRITTResponseBody(string listeClubsEventCRITTResult) {
            this.listeClubsEventCRITTResult = listeClubsEventCRITTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listeClubsCRITTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listeClubsCRITT", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.listeClubsCRITTRequestBody Body;
        
        public listeClubsCRITTRequest() {
        }
        
        public listeClubsCRITTRequest(Tools.FFJudoServices.listeClubsCRITTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listeClubsCRITTRequestBody {
        
        public listeClubsCRITTRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listeClubsCRITTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listeClubsCRITTResponse", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.listeClubsCRITTResponseBody Body;
        
        public listeClubsCRITTResponse() {
        }
        
        public listeClubsCRITTResponse(Tools.FFJudoServices.listeClubsCRITTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class listeClubsCRITTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listeClubsCRITTResult;
        
        public listeClubsCRITTResponseBody() {
        }
        
        public listeClubsCRITTResponseBody(string listeClubsCRITTResult) {
            this.listeClubsCRITTResult = listeClubsCRITTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listeCategoriesPoidsCRITTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listeCategoriesPoidsCRITT", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.listeCategoriesPoidsCRITTRequestBody Body;
        
        public listeCategoriesPoidsCRITTRequest() {
        }
        
        public listeCategoriesPoidsCRITTRequest(Tools.FFJudoServices.listeCategoriesPoidsCRITTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class listeCategoriesPoidsCRITTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Sexe;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Age;
        
        public listeCategoriesPoidsCRITTRequestBody() {
        }
        
        public listeCategoriesPoidsCRITTRequestBody(string Sexe, string Age) {
            this.Sexe = Sexe;
            this.Age = Age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listeCategoriesPoidsCRITTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listeCategoriesPoidsCRITTResponse", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.listeCategoriesPoidsCRITTResponseBody Body;
        
        public listeCategoriesPoidsCRITTResponse() {
        }
        
        public listeCategoriesPoidsCRITTResponse(Tools.FFJudoServices.listeCategoriesPoidsCRITTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class listeCategoriesPoidsCRITTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listeCategoriesPoidsCRITTResult;
        
        public listeCategoriesPoidsCRITTResponseBody() {
        }
        
        public listeCategoriesPoidsCRITTResponseBody(string listeCategoriesPoidsCRITTResult) {
            this.listeCategoriesPoidsCRITTResult = listeCategoriesPoidsCRITTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listeEventsCRITTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listeEventsCRITT", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.listeEventsCRITTRequestBody Body;
        
        public listeEventsCRITTRequest() {
        }
        
        public listeEventsCRITTRequest(Tools.FFJudoServices.listeEventsCRITTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class listeEventsCRITTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string structure;
        
        public listeEventsCRITTRequestBody() {
        }
        
        public listeEventsCRITTRequestBody(string login, string pwd, string structure) {
            this.login = login;
            this.pwd = pwd;
            this.structure = structure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listeEventsCRITTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listeEventsCRITTResponse", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.listeEventsCRITTResponseBody Body;
        
        public listeEventsCRITTResponse() {
        }
        
        public listeEventsCRITTResponse(Tools.FFJudoServices.listeEventsCRITTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class listeEventsCRITTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listeEventsCRITTResult;
        
        public listeEventsCRITTResponseBody() {
        }
        
        public listeEventsCRITTResponseBody(string listeEventsCRITTResult) {
            this.listeEventsCRITTResult = listeEventsCRITTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listePopulationCRITTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listePopulationCRITT", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.listePopulationCRITTRequestBody Body;
        
        public listePopulationCRITTRequest() {
        }
        
        public listePopulationCRITTRequest(Tools.FFJudoServices.listePopulationCRITTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class listePopulationCRITTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string structure;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string comite;
        
        public listePopulationCRITTRequestBody() {
        }
        
        public listePopulationCRITTRequestBody(string login, string pwd, string structure, string comite) {
            this.login = login;
            this.pwd = pwd;
            this.structure = structure;
            this.comite = comite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listePopulationCRITTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listePopulationCRITTResponse", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.listePopulationCRITTResponseBody Body;
        
        public listePopulationCRITTResponse() {
        }
        
        public listePopulationCRITTResponse(Tools.FFJudoServices.listePopulationCRITTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class listePopulationCRITTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listePopulationCRITTResult;
        
        public listePopulationCRITTResponseBody() {
        }
        
        public listePopulationCRITTResponseBody(string listePopulationCRITTResult) {
            this.listePopulationCRITTResult = listePopulationCRITTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class majResultatCRITTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="majResultatCRITT", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.majResultatCRITTRequestBody Body;
        
        public majResultatCRITTRequest() {
        }
        
        public majResultatCRITTRequest(Tools.FFJudoServices.majResultatCRITTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class majResultatCRITTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string structure;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string xml;
        
        public majResultatCRITTRequestBody() {
        }
        
        public majResultatCRITTRequestBody(string login, string pwd, string structure, string xml) {
            this.login = login;
            this.pwd = pwd;
            this.structure = structure;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class majResultatCRITTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="majResultatCRITTResponse", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.majResultatCRITTResponseBody Body;
        
        public majResultatCRITTResponse() {
        }
        
        public majResultatCRITTResponse(Tools.FFJudoServices.majResultatCRITTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class majResultatCRITTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string majResultatCRITTResult;
        
        public majResultatCRITTResponseBody() {
        }
        
        public majResultatCRITTResponseBody(string majResultatCRITTResult) {
            this.majResultatCRITTResult = majResultatCRITTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class majResultatFFJDARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="majResultatFFJDA", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.majResultatFFJDARequestBody Body;
        
        public majResultatFFJDARequest() {
        }
        
        public majResultatFFJDARequest(Tools.FFJudoServices.majResultatFFJDARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class majResultatFFJDARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string structure;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string xml;
        
        public majResultatFFJDARequestBody() {
        }
        
        public majResultatFFJDARequestBody(string login, string pwd, string structure, string xml) {
            this.login = login;
            this.pwd = pwd;
            this.structure = structure;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class majResultatFFJDAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="majResultatFFJDAResponse", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.majResultatFFJDAResponseBody Body;
        
        public majResultatFFJDAResponse() {
        }
        
        public majResultatFFJDAResponse(Tools.FFJudoServices.majResultatFFJDAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class majResultatFFJDAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string majResultatFFJDAResult;
        
        public majResultatFFJDAResponseBody() {
        }
        
        public majResultatFFJDAResponseBody(string majResultatFFJDAResult) {
            this.majResultatFFJDAResult = majResultatFFJDAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="test", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.testRequestBody Body;
        
        public testRequest() {
        }
        
        public testRequest(Tools.FFJudoServices.testRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class testRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public testRequestBody() {
        }
        
        public testRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="testResponse", Namespace="http://ffjda_critt.org/", Order=0)]
        public Tools.FFJudoServices.testResponseBody Body;
        
        public testResponse() {
        }
        
        public testResponse(Tools.FFJudoServices.testResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ffjda_critt.org/")]
    public partial class testResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string testResult;
        
        public testResponseBody() {
        }
        
        public testResponseBody(string testResult) {
            this.testResult = testResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Tools.FFJudoServices.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Tools.FFJudoServices.WebService1Soap>, Tools.FFJudoServices.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tools.FFJudoServices.listeInscriptionsCRITTResponse Tools.FFJudoServices.WebService1Soap.listeInscriptionsCRITT(Tools.FFJudoServices.listeInscriptionsCRITTRequest request) {
            return base.Channel.listeInscriptionsCRITT(request);
        }
        
        public string listeInscriptionsCRITT(int idEvent) {
            Tools.FFJudoServices.listeInscriptionsCRITTRequest inValue = new Tools.FFJudoServices.listeInscriptionsCRITTRequest();
            inValue.Body = new Tools.FFJudoServices.listeInscriptionsCRITTRequestBody();
            inValue.Body.idEvent = idEvent;
            Tools.FFJudoServices.listeInscriptionsCRITTResponse retVal = ((Tools.FFJudoServices.WebService1Soap)(this)).listeInscriptionsCRITT(inValue);
            return retVal.Body.listeInscriptionsCRITTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tools.FFJudoServices.listeClubsEventCRITTResponse Tools.FFJudoServices.WebService1Soap.listeClubsEventCRITT(Tools.FFJudoServices.listeClubsEventCRITTRequest request) {
            return base.Channel.listeClubsEventCRITT(request);
        }
        
        public string listeClubsEventCRITT(int idEvent) {
            Tools.FFJudoServices.listeClubsEventCRITTRequest inValue = new Tools.FFJudoServices.listeClubsEventCRITTRequest();
            inValue.Body = new Tools.FFJudoServices.listeClubsEventCRITTRequestBody();
            inValue.Body.idEvent = idEvent;
            Tools.FFJudoServices.listeClubsEventCRITTResponse retVal = ((Tools.FFJudoServices.WebService1Soap)(this)).listeClubsEventCRITT(inValue);
            return retVal.Body.listeClubsEventCRITTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tools.FFJudoServices.listeClubsCRITTResponse Tools.FFJudoServices.WebService1Soap.listeClubsCRITT(Tools.FFJudoServices.listeClubsCRITTRequest request) {
            return base.Channel.listeClubsCRITT(request);
        }
        
        public string listeClubsCRITT() {
            Tools.FFJudoServices.listeClubsCRITTRequest inValue = new Tools.FFJudoServices.listeClubsCRITTRequest();
            inValue.Body = new Tools.FFJudoServices.listeClubsCRITTRequestBody();
            Tools.FFJudoServices.listeClubsCRITTResponse retVal = ((Tools.FFJudoServices.WebService1Soap)(this)).listeClubsCRITT(inValue);
            return retVal.Body.listeClubsCRITTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tools.FFJudoServices.listeCategoriesPoidsCRITTResponse Tools.FFJudoServices.WebService1Soap.listeCategoriesPoidsCRITT(Tools.FFJudoServices.listeCategoriesPoidsCRITTRequest request) {
            return base.Channel.listeCategoriesPoidsCRITT(request);
        }
        
        public string listeCategoriesPoidsCRITT(string Sexe, string Age) {
            Tools.FFJudoServices.listeCategoriesPoidsCRITTRequest inValue = new Tools.FFJudoServices.listeCategoriesPoidsCRITTRequest();
            inValue.Body = new Tools.FFJudoServices.listeCategoriesPoidsCRITTRequestBody();
            inValue.Body.Sexe = Sexe;
            inValue.Body.Age = Age;
            Tools.FFJudoServices.listeCategoriesPoidsCRITTResponse retVal = ((Tools.FFJudoServices.WebService1Soap)(this)).listeCategoriesPoidsCRITT(inValue);
            return retVal.Body.listeCategoriesPoidsCRITTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tools.FFJudoServices.listeEventsCRITTResponse Tools.FFJudoServices.WebService1Soap.listeEventsCRITT(Tools.FFJudoServices.listeEventsCRITTRequest request) {
            return base.Channel.listeEventsCRITT(request);
        }
        
        public string listeEventsCRITT(string login, string pwd, string structure) {
            Tools.FFJudoServices.listeEventsCRITTRequest inValue = new Tools.FFJudoServices.listeEventsCRITTRequest();
            inValue.Body = new Tools.FFJudoServices.listeEventsCRITTRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.structure = structure;
            Tools.FFJudoServices.listeEventsCRITTResponse retVal = ((Tools.FFJudoServices.WebService1Soap)(this)).listeEventsCRITT(inValue);
            return retVal.Body.listeEventsCRITTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tools.FFJudoServices.listePopulationCRITTResponse Tools.FFJudoServices.WebService1Soap.listePopulationCRITT(Tools.FFJudoServices.listePopulationCRITTRequest request) {
            return base.Channel.listePopulationCRITT(request);
        }
        
        public string listePopulationCRITT(string login, string pwd, string structure, string comite) {
            Tools.FFJudoServices.listePopulationCRITTRequest inValue = new Tools.FFJudoServices.listePopulationCRITTRequest();
            inValue.Body = new Tools.FFJudoServices.listePopulationCRITTRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.structure = structure;
            inValue.Body.comite = comite;
            Tools.FFJudoServices.listePopulationCRITTResponse retVal = ((Tools.FFJudoServices.WebService1Soap)(this)).listePopulationCRITT(inValue);
            return retVal.Body.listePopulationCRITTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tools.FFJudoServices.majResultatCRITTResponse Tools.FFJudoServices.WebService1Soap.majResultatCRITT(Tools.FFJudoServices.majResultatCRITTRequest request) {
            return base.Channel.majResultatCRITT(request);
        }
        
        public string majResultatCRITT(string login, string pwd, string structure, string xml) {
            Tools.FFJudoServices.majResultatCRITTRequest inValue = new Tools.FFJudoServices.majResultatCRITTRequest();
            inValue.Body = new Tools.FFJudoServices.majResultatCRITTRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.structure = structure;
            inValue.Body.xml = xml;
            Tools.FFJudoServices.majResultatCRITTResponse retVal = ((Tools.FFJudoServices.WebService1Soap)(this)).majResultatCRITT(inValue);
            return retVal.Body.majResultatCRITTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tools.FFJudoServices.majResultatFFJDAResponse Tools.FFJudoServices.WebService1Soap.majResultatFFJDA(Tools.FFJudoServices.majResultatFFJDARequest request) {
            return base.Channel.majResultatFFJDA(request);
        }
        
        public string majResultatFFJDA(string login, string pwd, string structure, string xml) {
            Tools.FFJudoServices.majResultatFFJDARequest inValue = new Tools.FFJudoServices.majResultatFFJDARequest();
            inValue.Body = new Tools.FFJudoServices.majResultatFFJDARequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.structure = structure;
            inValue.Body.xml = xml;
            Tools.FFJudoServices.majResultatFFJDAResponse retVal = ((Tools.FFJudoServices.WebService1Soap)(this)).majResultatFFJDA(inValue);
            return retVal.Body.majResultatFFJDAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tools.FFJudoServices.testResponse Tools.FFJudoServices.WebService1Soap.test(Tools.FFJudoServices.testRequest request) {
            return base.Channel.test(request);
        }
        
        public string test(string xml) {
            Tools.FFJudoServices.testRequest inValue = new Tools.FFJudoServices.testRequest();
            inValue.Body = new Tools.FFJudoServices.testRequestBody();
            inValue.Body.xml = xml;
            Tools.FFJudoServices.testResponse retVal = ((Tools.FFJudoServices.WebService1Soap)(this)).test(inValue);
            return retVal.Body.testResult;
        }
    }
}
