<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
	<TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
	<SupportedOSPlatform>Windows</SupportedOSPlatform>
    <OutputType>WinExe</OutputType>
	<ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <LangVersion>latest</LangVersion>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>C:\Users\dgarr\Documents\Sport\Judo\MDJ\Publish_Publication_Suivi_Competition\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ProductName>Publication Suivi Competition</ProductName>
    <PublisherName>Comité du Rhone-Lyon Metropole Judo</PublisherName>
    <OpenBrowserOnPublish>false</OpenBrowserOnPublish>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.1.0.0</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <CreateDesktopShortcut>true</CreateDesktopShortcut>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>CD_ROM;Debug;DVD-5;Release;SingleImage</Configurations>
    <ApplicationIcon>Logo_AppPublication.ico</ApplicationIcon>
    <TargetZone>LocalIntranet</TargetZone>
    <GenerateManifests>false</GenerateManifests>
    <ManifestCertificateThumbprint>9C39AA171DFCECA8008F6C39E70C754B9415D2DF</ManifestCertificateThumbprint>
    <ManifestKeyFile>AppPublication_TemporaryKey.pfx</ManifestKeyFile>
    <SignManifests>false</SignManifests>
    <StartupObject>AppPublication.App</StartupObject>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>True</Optimize>
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='CD_ROM|AnyCPU'">
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DVD-5|AnyCPU'">
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='SingleImage|AnyCPU'">
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="EPPlus">
      <HintPath>..\packages\EPPlus.dll</HintPath>
    </Reference>
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="HandyControl.Lang.fr" Version="3.5.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="NLog" Version="6.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters.CoreServices" Version="2.3.0" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="SharpVectors.Wpf" Version="1.8.5" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Documentation\ManuelUtilisateur.pdf" />
    <None Include="Documentation\PublicationSuiviCompetition - Manuel d%27utilisation.pptx" />
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FranceJudo.Core\FranceJudo.Core.csproj" />
    <ProjectReference Include="..\FranceJudo.Metier\FranceJudo.Metier.csproj" />
    <ProjectReference Include="..\FranceJudo.UI\FranceJudo.UI.csproj" />
    <ProjectReference Include="..\JudoClient\JudoClient.csproj" />
    <ProjectReference Include="..\KernelImpl\KernelImpl.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="France-Judo.ico" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.8">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.8 %28x86 et x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Logo_AppPublication.ico" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="nlog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="SpicNSpan" AfterTargets="Clean">
    <RemoveDir Directories="$(TargetDir)" />
    <RemoveDir Directories="$(ProjectDir)$(BaseIntermediateOutputPath)" />
  </Target>
</Project>