<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Configurations>CD_ROM;Debug;DVD-5;Release;SingleImage</Configurations>
    <AssemblyTitle>FranceJudo.Metier</AssemblyTitle>
    <Product>FranceJudo.Metier</Product>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\Site\img\info-32.png" />
    <None Remove="Resources\Site\img\speech_bubble-32.png" />
    <None Remove="Resources\Site\img\statistics-32.png" />
    <None Remove="Resources\Site\img\tree_structure-32.png" />
    <None Remove="Resources\Site\style\style-statistiques.css" />
    <None Remove="Resources\Site\xslt\groupe_statistiques_site.xslt" />
    <None Remove="Resources\Site\xslt\nom_structure.xslt" />
    <None Remove="Resources\Site\xslt\statistiques_site.xslt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.1.4" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Referentiels\c_ages.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Referentiels\c_poids.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Referentiels\g_temps.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Referentiels\grades.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Referentiels\PublicationFFJudo.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Referentiels\s_comites.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Referentiels\s_ligues.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Referentiels\structures.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Site\img\info-32.png" />
    <EmbeddedResource Include="Resources\Site\img\speech_bubble-32.png" />
    <EmbeddedResource Include="Resources\Site\img\statistics-32.png" />
    <EmbeddedResource Include="Resources\Site\img\tree_structure-32.png" />
    <EmbeddedResource Include="Resources\Site\style\style-statistiques.css" />
    <EmbeddedResource Include="Resources\Site\xslt\groupe_statistiques_site.xslt" />
    <EmbeddedResource Include="Resources\Site\xslt\nom_structure.xslt" />
    <EmbeddedResource Include="Resources\Site\xslt\statistiques_site.xslt" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Media\Images\France-Judo.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Media\Images\France-Judo.jpg" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Media\Images\France-Judo.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Arbitre1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Arbitre2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Arbitre3.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Classement-final1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Classement-final2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Classement-poule1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Classement-poule2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Classement-tableau1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Classement-tableau2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Commissaires1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Commissaires2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Commissaires3.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Epreuves1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Epreuves2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Exporte-XML.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Exporte-XML2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Exporte-XML3.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Formule1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Formule2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Inscription1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Inscription2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Judoka1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Judoka2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Judoka3.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Parametres1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Parametres2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Parametres3.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Tirage-poule1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Tirage-poule2.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Tirage-tableau1.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Media\Icons\Tirage-tableau2.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Media\Images\Tournoi_Judo.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FranceJudo.Core\FranceJudo.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\badge-1st-32.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\checked_checkbox-32.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\down_circular-32.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\equal-sign-32.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\home-32.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\logo-France-Judo-Rhone.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\logo-France-Judo.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\refresh-32.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\repeat-32.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\sablier.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\starter-32.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\unchecked_checkbox-32.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\up_circular-32.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\img\winner-32.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\js\site-animation.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\js\site-display.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\style\style-classement.css" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\style\style-common.css" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\style\style-ecran-appel.css" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\style\style-poule.css" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\style\style-tableau.css" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\style\w3.css" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\affectation_tapis_site.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\avancement_site.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\classement_final_site.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\classement_site.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\ecrans_appel_site.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\engagements_site.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\entete.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\feuille_competition_site.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\feuille_matchs_site.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\feuille_resultat_site.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\footer_script_site.xslt" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\groupe_engagements_site.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\index_site.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\niveau_tour_combat.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\panel_epreuve.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Site\xslt\prochains_combats_site.xslt">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <Target Name="GenerateLoggerResource" BeforeTargets="BeforeBuild">
    <MakeDir Directories="$(IntermediateOutputPath)JsDist" />
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
      <LoggerJsContent>
        window.Logger = {	
            log: function() { if (typeof console !== 'undefined') console.log.apply(console, arguments); },
            warn: function() { if (typeof console !== 'undefined') console.warn.apply(console, arguments); },
            error: function() { if (typeof console !== 'undefined') console.error.apply(console, arguments); }
        };
      </LoggerJsContent>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
      <LoggerJsContent>
        window.Logger = {
            log: function() {},
            warn: function() {},
            error: function() { if (typeof console !== 'undefined') console.error.apply(console, arguments); }
        };
      </LoggerJsContent>
    </PropertyGroup>
    <WriteLinesToFile File="$(IntermediateOutputPath)JsDist\logger.js" Lines="$(LoggerJsContent)" Overwrite="true" />
    <ItemGroup>
		<InternalsVisibleTo Include="FranceJudo.Metier.Tests" />
      <EmbeddedResource Include="$(IntermediateOutputPath)JsDist\logger.js">
        <LogicalName>FranceJudo.Metier.Resources.Site.js.site-logger.js</LogicalName>
      </EmbeddedResource>
    </ItemGroup>
  </Target>
</Project>